[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
presale = "C9pV31WQ6AgBWh2bbujmGSPvvEZLQsdgrCQxJf17rw98"

[programs.devnet]
presale = "HmaGgT6pQHRC9X8XAjCojM9LLoPkdQCbR5YUNqyjji2t"

[programs.mainnet]
presale = "EJmaTQvanPtAhj3Ehv5ZboCnrGtNraMqK4qnPBJio9Eo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
