[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
presale = "91QyicMu8N2m5U9SrBbJ6NiXRHH3c7nWaJnPkmVkWvtu"

[programs.devnet]
presale = "91QyicMu8N2m5U9SrBbJ6NiXRHH3c7nWaJnPkmVkWvtu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
