[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
presale = "5GLrJSNnMrNdE9dCFNDAR7diy6eqTCfwXX6Vcxwd4LjD"

[programs.devnet]
presale = "HmaGgT6pQHRC9X8XAjCojM9LLoPkdQCbR5YUNqyjji2t"

[programs.mainnet]
presale = "HmaGgT6pQHRC9X8XAjCojM9LLoPkdQCbR5YUNqyjji2t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
