[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
presale = "DcX7NVTtmtUtfmiNQ3bZwov9bKDRpjj7Z8bY61MYPdew"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/gritzb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
